import { Row, Col } from "antd";

export default function Home() {
  return (
    <div>
      <Row>
        <Col>
          <Row>
            <Col>
              <Row>
                <Col>
                  <Row>
                    <Col>
                      <Row>
                        <Col>
                          <Row>
                            <Col>
                              <Row>
                                <Col>
                                  <Row>
                                    <Col>
                                      <Row>
                                        <Col>
                                          <Row>
                                            <Col>
                                              <Row>
                                                <Col>
                                                  <Row>
                                                    <Col>
                                                      <Row>
                                                        <Col>
                                                          <Row>
                                                            <Col>
                                                              <Row>
                                                                <Col>
                                                                  <Row>
                                                                    <Col>
                                                                      <Row>
                                                                        <Col>
                                                                          <Row>
                                                                            <Col>
                                                                              <Row>
                                                                                <Col>
                                                                                  <Row>
                                                                                    <Col>
                                                                                      <Row>
                                                                                        <Col>
                                                                                          <Row>
                                                                                            <Col>
                                                                                              <Row>
                                                                                                <Col>
                                                                                                  <Row>
                                                                                                    <Col>
                                                                                                      <Row>
                                                                                                        <Col>
                                                                                                          <Row>
                                                                                                            <Col>
                                                                                                              <Row>
                                                                                                                <Col>
                                                                                                                  <Row>
                                                                                                                    <Col>
                                                                                                                      <Row>
                                                                                                                        <Col>
                                                                                                                          <Row>
                                                                                                                            <Col>
                                                                                                                              <Row>
                                                                                                                                <Col>
                                                                                                                                  <Row>
                                                                                                                                    <Col>
                                                                                                                                      <Row>
                                                                                                                                        <Col>
                                                                                                                                          <Row>
                                                                                                                                            <Col>
                                                                                                                                              <Row>
                                                                                                                                                <Col>
                                                                                                                                                  <Row>
                                                                                                                                                    <Col>
                                                                                                                                                      <Row>
                                                                                                                                                        <Col>
                                                                                                                                                          <Row>
                                                                                                                                                            <Col>
                                                                                                                                                              <Row>
                                                                                                                                                                <Col>
                                                                                                                                                                  <Row>
                                                                                                                                                                    <Col>
                                                                                                                                                                      <Row>
                                                                                                                                                                        <Col>
                                                                                                                                                                          <Row>
                                                                                                                                                                            <Col>
                                                                                                                                                                              <Row>
                                                                                                                                                                                <Col>
                                                                                                                                                                                  <Row>
                                                                                                                                                                                    <Col>
                                                                                                                                                                                      <Row>
                                                                                                                                                                                        <Col>
                                                                                                                                                                                          <Row>
                                                                                                                                                                                            <Col>
                                                                                                                                                                                              <Row>
                                                                                                                                                                                                <Col>
                                                                                                                                                                                                  <Row>
                                                                                                                                                                                                    <Col>
                                                                                                                                                                                                      <Row>
                                                                                                                                                                                                        <Col>
                                                                                                                                                                                                          <Row>
                                                                                                                                                                                                            <Col>
                                                                                                                                                                                                              <Row>
                                                                                                                                                                                                                <Col>
                                                                                                                                                                                                                  <Row>
                                                                                                                                                                                                                    <Col>
                                                                                                                                                                                                                      <Row>
                                                                                                                                                                                                                        <Col></Col>
                                                                                                                                                                                                                      </Row>
                                                                                                                                                                                                                    </Col>
                                                                                                                                                                                                                  </Row>
                                                                                                                                                                                                                </Col>
                                                                                                                                                                                                              </Row>
                                                                                                                                                                                                            </Col>
                                                                                                                                                                                                          </Row>
                                                                                                                                                                                                        </Col>
                                                                                                                                                                                                      </Row>
                                                                                                                                                                                                    </Col>
                                                                                                                                                                                                  </Row>
                                                                                                                                                                                                </Col>
                                                                                                                                                                                              </Row>
                                                                                                                                                                                            </Col>
                                                                                                                                                                                          </Row>
                                                                                                                                                                                        </Col>
                                                                                                                                                                                      </Row>
                                                                                                                                                                                    </Col>
                                                                                                                                                                                  </Row>
                                                                                                                                                                                </Col>
                                                                                                                                                                              </Row>
                                                                                                                                                                            </Col>
                                                                                                                                                                          </Row>
                                                                                                                                                                        </Col>
                                                                                                                                                                      </Row>
                                                                                                                                                                    </Col>
                                                                                                                                                                  </Row>
                                                                                                                                                                </Col>
                                                                                                                                                              </Row>
                                                                                                                                                            </Col>
                                                                                                                                                          </Row>
                                                                                                                                                        </Col>
                                                                                                                                                      </Row>
                                                                                                                                                    </Col>
                                                                                                                                                  </Row>
                                                                                                                                                </Col>
                                                                                                                                              </Row>
                                                                                                                                            </Col>
                                                                                                                                          </Row>
                                                                                                                                        </Col>
                                                                                                                                      </Row>
                                                                                                                                    </Col>
                                                                                                                                  </Row>
                                                                                                                                </Col>
                                                                                                                              </Row>
                                                                                                                            </Col>
                                                                                                                          </Row>
                                                                                                                        </Col>
                                                                                                                      </Row>
                                                                                                                    </Col>
                                                                                                                  </Row>
                                                                                                                </Col>
                                                                                                              </Row>
                                                                                                            </Col>
                                                                                                          </Row>
                                                                                                        </Col>
                                                                                                      </Row>
                                                                                                    </Col>
                                                                                                  </Row>
                                                                                                </Col>
                                                                                              </Row>
                                                                                            </Col>
                                                                                          </Row>
                                                                                        </Col>
                                                                                      </Row>
                                                                                    </Col>
                                                                                  </Row>
                                                                                </Col>
                                                                              </Row>
                                                                            </Col>
                                                                          </Row>
                                                                        </Col>
                                                                      </Row>
                                                                    </Col>
                                                                  </Row>
                                                                </Col>
                                                              </Row>
                                                            </Col>
                                                          </Row>
                                                        </Col>
                                                      </Row>
                                                    </Col>
                                                  </Row>
                                                </Col>
                                              </Row>
                                            </Col>
                                          </Row>
                                        </Col>
                                      </Row>
                                    </Col>
                                  </Row>
                                </Col>
                              </Row>
                            </Col>
                          </Row>
                        </Col>
                      </Row>
                    </Col>
                  </Row>
                </Col>
              </Row>
            </Col>
          </Row>
        </Col>
      </Row>
    </div>
  );
}
export async function getServerSideProps() {
  return { props: {} };
}
